services:
  - type: web
    name: cratejuice-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000
    healthCheckPath: /health